<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:29
         compiled from assignment_view_main_grade.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'assignment_view_main_grade.html', 4, false),)), $this); ?>
<?php echo '<div class="outerdiv align-center"><form id="assignment_form';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" onsubmit="return false;"><input type="hidden" name="action" value="assignment_action_main_grade" /><input type="hidden" name="assignment_id" value="';  echo ((is_array($_tmp=$this->_tpl_vars['action']['assignment']['assignment_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" /><input type="hidden" name="submit_id" value="';  echo ((is_array($_tmp=$this->_tpl_vars['action']['submit_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" /><table class="outer" summary=""><tr class="row"><th class="nowrap">';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['assignment_grade'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '</th><td><select name="grade_value"><option value=""';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['submitter']['submit_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ASSIGNMENT_SUBMIT_FLAG_GRADED )):  echo ' selected="selected"';  endif;  echo '>';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['assignment_resubmitted'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '</option>';  $_from = ((is_array($_tmp=$this->_tpl_vars['action']['gradeValues'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['gradeValue']):
 echo '<option value="';  echo ((is_array($_tmp=$this->_tpl_vars['gradeValue']['grade_value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['submitter']['grade_value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == ((is_array($_tmp=$this->_tpl_vars['gradeValue']['grade_value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) )):  echo ' selected="selected"';  endif;  echo '>';  echo ((is_array($_tmp=$this->_tpl_vars['gradeValue']['grade_value'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '</option>';  endforeach; endif; unset($_from);  echo '</select></td></tr></table><div class="btn-bottom"><input name="regist_btn" type="button" class="btn-width lined_btn" value="';  echo $this->_tpl_vars['lang']['_regist'];  echo '" onclick="assignmentCls[\'';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '\'].gradeReport(\'';  echo ((is_array($_tmp=$_SESSION['assignment']['id'][$this->_tpl_vars['block_id']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '\', this.form); return false;" /><input name="cancel_btn" type="button" class="btn-width lined_btn" value="';  echo $this->_tpl_vars['lang']['_cancel'];  echo '" onclick=\'commonCls.removeBlock("';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"); return false;\' /></div></form></div>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../assignment_script.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo ''; ?>