<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:29
         compiled from assignment_view_edit_list.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'sprintf', 'assignment_view_edit_list.html', 5, false),array('modifier', 'escape', 'assignment_view_edit_list.html', 5, false),array('modifier', 'timezone_date_format', 'assignment_view_edit_list.html', 47, false),)), $this); ?>
<?php echo '';  echo '<div class="top_description">';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['_list_desc'])) ? $this->_run_mod_handler('sprintf', true, $_tmp, ((is_array($_tmp=$this->_tpl_vars['lang']['assignment_mod_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))) : sprintf($_tmp, ((is_array($_tmp=$this->_tpl_vars['lang']['assignment_mod_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))));  echo '</div><form id="assignment_form';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" action="#" onsubmit="return false;"><table class="grid_header" summary="';  echo $this->_tpl_vars['lang']['assignment_list_summary'];  echo '"><tr><th class="grid_change_disp" scope="col"></th><th class="_sort_assignment_name assignment_grid_name" scope="col">';  echo $this->_tpl_vars['lang']['assignment_assignment_name'];  echo '</th><th class="_sort_activity assignment_grid_operate" scope="col">';  echo $this->_tpl_vars['lang']['assignment_activity'];  echo '</th><th class="_sort_insert_user_name assignment_grid_creator" scope="col">';  echo $this->_tpl_vars['lang']['_creator'];  echo '</th><th class="_sort_insert_time assignment_grid_create_date" scope="col">';  echo $this->_tpl_vars['lang']['_create_date'];  echo '</th><th class="assignment_grid_manage">';  echo $this->_tpl_vars['lang']['_manage'];  echo '</th></tr></table><table class="grid assignment_grid_table" summary="';  echo $this->_tpl_vars['lang']['assignment_list_summary'];  echo '">';  $_from = ((is_array($_tmp=$this->_tpl_vars['action']['assignments'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['assignment']):
 echo '<tr id="assignment_row_tr';  echo ((is_array($_tmp=$this->_tpl_vars['assignment']['assignment_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" class="grid_row';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['assignment_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == ((is_array($_tmp=$this->_tpl_vars['assignment']['assignment_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) )):  echo ' highlight';  endif;  echo '"><td class="grid_change_disp">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "assignment_view_edit_list_current.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td><td class="assignment_grid_name">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "assignment_view_edit_list_name.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td><td class="assignment_grid_operate">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "assignment_view_edit_list_operate.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td><td class=" assignment_grid_creator">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "assignment_view_handle.html", 'smarty_include_vars' => array('handle' => $this->_tpl_vars['assignment']['insert_user_name'],'user_id' => ((is_array($_tmp=$this->_tpl_vars['assignment']['insert_user_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td><td class="assignment_grid_create_date">';  echo ((is_array($_tmp=$this->_tpl_vars['assignment']['insert_time'])) ? $this->_run_mod_handler('timezone_date_format', true, $_tmp, ((is_array($_tmp=$this->_tpl_vars['lang']['_date_format'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))) : timezone_date_format($_tmp, ((is_array($_tmp=$this->_tpl_vars['lang']['_date_format'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))));  echo '</td><td class="assignment_grid_manage">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "assignment_view_edit_list_manage.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td></tr>';  endforeach; endif; unset($_from);  echo '</table></form>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../assignment_script.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '<script class="nc_script" type="text/javascript">var opts = {prefetchBuffer:false,sort:true,requestParameters:new Array("scroll=';  echo ((is_array($_tmp=@_ON)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"),onSendCallback:function() {assignmentCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].checkCurrent();}};assignmentCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].liveGrid = new compLiveGrid("';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '", ';  echo ((is_array($_tmp=$this->_tpl_vars['action']['visibleRows'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo ', ';  echo ((is_array($_tmp=$this->_tpl_vars['action']['assignmentCount'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo ', "assignment_view_edit_list", opts);var opts = null;assignmentCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].assignment_id = "';  echo ((is_array($_tmp=$this->_tpl_vars['action']['assignment_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '";</script>'; ?>