<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:30
         compiled from bbs_mobile_flat.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'bbs_mobile_flat.html', 4, false),array('modifier', 'truncate', 'bbs_mobile_flat.html', 17, false),)), $this); ?>
<?php echo '';  echo '<dl>';  $_from = ((is_array($_tmp=$this->_tpl_vars['action']['posts'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['post']):
 echo '';  if (((is_array($_tmp=$this->_tpl_vars['post']['parent_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '0'):  echo '<dd><div>';  else:  echo '<dt>';  endif;  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "bbs_mobile_subject.html", 'smarty_include_vars' => array('display_type' => 'list')));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '<span style="font-size:small;">';  if (( ((is_array($_tmp=$_SESSION['_smartphone_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '<div style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">';  echo ((is_array($_tmp=$this->_tpl_vars['post']['body'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '</div>';  else:  echo '';  echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['post']['body'])) ? $this->_run_mod_handler('truncate', true, $_tmp, ((is_array($_tmp=@BBS_MOBILE_POST_BODY_LEN)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')), ((is_array($_tmp=@_SEARCH_MORE)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')), true) : smarty_modifier_truncate($_tmp, ((is_array($_tmp=@BBS_MOBILE_POST_BODY_LEN)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')), ((is_array($_tmp=@_SEARCH_MORE)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')), true)))) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '';  endif;  echo '</span>';  if (((is_array($_tmp=$this->_tpl_vars['post']['parent_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != '0'):  echo '</div></dd>';  else:  echo '</dt>';  endif;  echo '';  endforeach; endif; unset($_from);  echo '</dl>'; ?>