<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:30
         compiled from bbs_view_edit_list.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'sprintf', 'bbs_view_edit_list.html', 5, false),array('modifier', 'escape', 'bbs_view_edit_list.html', 5, false),array('modifier', 'timezone_date_format', 'bbs_view_edit_list.html', 46, false),)), $this); ?>
<?php echo '';  echo '<div class="outerdiv"><div class="top_description">';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['_list_desc'])) ? $this->_run_mod_handler('sprintf', true, $_tmp, ((is_array($_tmp=$this->_tpl_vars['lang']['bbs_bbs'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))) : sprintf($_tmp, ((is_array($_tmp=$this->_tpl_vars['lang']['bbs_bbs'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))));  echo '</div><table class="grid_header" summary="';  echo $this->_tpl_vars['lang']['bbs_list_summary'];  echo '"><tr><th class="grid_change_disp" scope="col"></th><th class="_sort_bbs_name grid_name" scope="col">';  echo $this->_tpl_vars['lang']['bbs_bbs_name'];  echo '</th><th class="_sort_activity grid_operate" scope="col">';  echo $this->_tpl_vars['lang']['bbs_activity'];  echo '</th><th class="_sort_insert_user_name grid_creator" scope="col">';  echo $this->_tpl_vars['lang']['_creator'];  echo '</th><th class="_sort_insert_time grid_create_date" scope="col">';  echo $this->_tpl_vars['lang']['_create_date'];  echo '</th><th class="grid_manage">';  echo $this->_tpl_vars['lang']['_manage'];  echo '</th></tr></table><table class="grid bbs_grid_table" summary="';  echo $this->_tpl_vars['lang']['bbs_list_summary'];  echo '">';  $_from = ((is_array($_tmp=$this->_tpl_vars['action']['bbses'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['bbs']):
 echo '<tr id="bbs_current_row';  echo ((is_array($_tmp=$this->_tpl_vars['bbs']['bbs_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" class="grid_row"><td class="grid_change_disp">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "bbs_view_edit_list_current.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td><td class="grid_name">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "bbs_view_edit_list_name.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td><td class="grid_operate">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "bbs_view_edit_list_operate.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td><td class="grid_creator">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "bbs_view_handle.html", 'smarty_include_vars' => array('handle' => $this->_tpl_vars['bbs']['insert_user_name'],'user_id' => ((is_array($_tmp=$this->_tpl_vars['bbs']['insert_user_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td><td class="grid_create_date">';  echo ((is_array($_tmp=$this->_tpl_vars['bbs']['insert_time'])) ? $this->_run_mod_handler('timezone_date_format', true, $_tmp, ((is_array($_tmp=$this->_tpl_vars['lang']['_date_format'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))) : timezone_date_format($_tmp, ((is_array($_tmp=$this->_tpl_vars['lang']['_date_format'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))));  echo '</td><td class="grid_manage">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "bbs_view_edit_list_manage.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td></tr>';  endforeach; endif; unset($_from);  echo '</table></div>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../bbs_script.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '<script class="nc_script" type="text/javascript">var opts = {prefetchBuffer:false,sort:true,requestParameters:new Array("scroll=';  echo ((is_array($_tmp=@_ON)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"),onSendCallback:function() {bbsCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].checkCurrent();}};new compLiveGrid("';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '", ';  echo ((is_array($_tmp=$this->_tpl_vars['action']['visibleRows'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo ', ';  echo ((is_array($_tmp=$this->_tpl_vars['action']['bbsCount'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo ', "bbs_view_edit_list", opts);opts = null;bbsCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].currentBbsID = "';  echo ((is_array($_tmp=$this->_tpl_vars['action']['currentBbsID'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '";bbsCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].checkCurrent();</script>'; ?>