<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:30
         compiled from cabinet_view_main_context.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'cabinet_view_main_context.html', 4, false),)), $this); ?>
<?php echo '<div class="popupClass contextMenu cabinet_context_menu">';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['reference'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _OFF && ((is_array($_tmp=$this->_tpl_vars['action']['file']['hasEditAuthority'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "cabinet_view_main_context_item.html", 'smarty_include_vars' => array('item_type' => 'edit','file_id' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_type' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_type'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_name' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  else:  echo '<div class="contextDisableRow">';  echo $this->_tpl_vars['lang']['cabinet_edit'];  echo '</div>';  endif;  echo '';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['reference'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _OFF && ((is_array($_tmp=$this->_tpl_vars['action']['file']['hasEditAuthority'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON && ((is_array($_tmp=$this->_tpl_vars['action']['cabinet']['hasAddAuthority'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "cabinet_view_main_context_item.html", 'smarty_include_vars' => array('item_type' => 'move','file_id' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_type' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_type'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_name' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  else:  echo '<div class="contextDisableRow">';  echo $this->_tpl_vars['lang']['cabinet_move'];  echo '</div>';  endif;  echo '';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['reference'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _OFF && ((is_array($_tmp=$this->_tpl_vars['action']['file']['hasEditAuthority'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "cabinet_view_main_context_item.html", 'smarty_include_vars' => array('item_type' => 'delete','file_id' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_type' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_type'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_name' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  else:  echo '<div class="contextDisableRow">';  echo $this->_tpl_vars['lang']['cabinet_delete'];  echo '</div>';  endif;  echo '<div class="hr"></div>';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['cabinet']['compress_download'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "cabinet_view_main_context_item.html", 'smarty_include_vars' => array('item_type' => 'compress_download','file_id' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_type' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_type'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_name' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  elseif (( ((is_array($_tmp=$this->_tpl_vars['action']['reference'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _OFF && ((is_array($_tmp=$this->_tpl_vars['action']['file']['hasEditAuthority'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON && ((is_array($_tmp=$this->_tpl_vars['action']['cabinet']['hasAddAuthority'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "cabinet_view_main_context_item.html", 'smarty_include_vars' => array('item_type' => 'compress','file_id' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_type' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_type'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_name' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  else:  echo '<div class="contextDisableRow">';  echo $this->_tpl_vars['lang']['cabinet_compression'];  echo '</div>';  endif;  echo '';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['reference'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _OFF && ((is_array($_tmp=$this->_tpl_vars['action']['file']['decompress_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) && ((is_array($_tmp=$this->_tpl_vars['action']['file']['hasEditAuthority'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON && ((is_array($_tmp=$this->_tpl_vars['action']['cabinet']['hasAddAuthority'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "cabinet_view_main_context_item.html", 'smarty_include_vars' => array('item_type' => 'decompress','file_id' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_type' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_type'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_name' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  else:  echo '<div class="contextDisableRow">';  echo $this->_tpl_vars['lang']['cabinet_decompression'];  echo '</div>';  endif;  echo '<div class="hr"></div>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "cabinet_view_main_context_item.html", 'smarty_include_vars' => array('item_type' => 'property','file_id' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_type' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_type'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'file_name' => ((is_array($_tmp=$this->_tpl_vars['action']['file']['file_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</div>'; ?>