<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:30
         compiled from circular_select_member_list.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'circular_select_member_list.html', 3, false),array('modifier', 'get_themes_image', 'circular_select_member_list.html', 13, false),)), $this); ?>
<?php echo '';  echo '<table ';  if (((is_array($_tmp=$this->_tpl_vars['action_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 'circular_view_main_create'):  echo 'class="circular_select_member_table"';  endif;  echo '><tr><td><select class="circular_select_room_boxsize" size="1" id="selected_room_id';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" name="selected_room_id" onchange="circularCls[\'';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '\'].getRoomUser(); return false;">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "circular_select_room_list.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</select></td><td class="align-left valign-middle">';  if (((is_array($_tmp=$this->_tpl_vars['action_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 'circular_view_main_create'):  echo '<a class="syslink" href="#" onclick="circularCls[\'';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '\'].popupEditGroup(event);return false;"><img class="icon" src="';  echo ((is_array($_tmp='edit.gif')) ? $this->_run_mod_handler('get_themes_image', true, $_tmp) : get_themes_image($_tmp));  echo '" title="';  echo $this->_tpl_vars['lang']['circular_edit_group_title'];  echo '" alt="';  echo $this->_tpl_vars['lang']['circular_edit_group_title'];  echo '" /></a>';  endif;  echo '</td><td>';  if (((is_array($_tmp=$this->_tpl_vars['action_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 'circular_view_main_group_init'):  echo '<div class="align-right circular_padding"><span class="syslink"><a class="syslink" href="#" title="';  echo $this->_tpl_vars['lang']['circular_group_clear_title'];  echo '" onclick="circularCls[\'';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '\'].clearGroupInfo();return false;">';  echo $this->_tpl_vars['lang']['circular_group_clear'];  echo '</a></span></div>';  endif;  echo '</td></tr><tr><td class="align-center"><div id="room_users';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "circular_select_user_list.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</div><input type="button" value="';  echo $this->_tpl_vars['lang']['_btn_select_all'];  echo '" onclick="circularCls[\'';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '\'].selectAllUser(\'group\'); return false;" /></td><td class="valign-middle"><input type="button" value="';  echo $this->_tpl_vars['lang']['_btn_add_arrow'];  echo '" onclick="circularCls[\'';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '\'].moveUser(\'add\'); return false;" /><br /><br /><input type="button" value="';  echo $this->_tpl_vars['lang']['_btn_del_arrow'];  echo '" onclick="circularCls[\'';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '\'].moveUser(\'remove\'); return false;" /><br /><br /></td><td class="align-center"><div><select class="circular_select_user_boxsize" id="selected_user_list';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" name="selected_user_list" size="8" multiple>';  if (((is_array($_tmp=$this->_tpl_vars['action_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 'circular_view_main_create'):  echo '';  if (is_array ( ((is_array($_tmp=$this->_tpl_vars['action']['circular_user_list'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) )):  echo '';  $_from = ((is_array($_tmp=$this->_tpl_vars['action']['circular_user_list'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['item']):
 echo '<option value="';  echo ((is_array($_tmp=$this->_tpl_vars['item']['receive_user_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  echo ((is_array($_tmp=$this->_tpl_vars['item']['handle'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '</option>';  endforeach; endif; unset($_from);  echo '';  endif;  echo '';  else:  echo '';  if (is_array ( ((is_array($_tmp=$this->_tpl_vars['action']['group_info']['group_member'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) )):  echo '';  $_from = ((is_array($_tmp=$this->_tpl_vars['action']['group_info']['group_member'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['item']):
 echo '<option value="';  echo ((is_array($_tmp=$this->_tpl_vars['item']['user_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  echo ((is_array($_tmp=$this->_tpl_vars['item']['handle'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '</option>';  endforeach; endif; unset($_from);  echo '';  endif;  echo '';  endif;  echo '</select></div><input type="button" value="';  echo $this->_tpl_vars['lang']['_btn_select_all'];  echo '" onclick="circularCls[\'';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '\'].selectAllUser(\'selected\'); return false;" /></td></tr></table>'; ?>