<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:31
         compiled from calendar_view_edit_select_room.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'calendar_view_edit_select_room.html', 5, false),array('modifier', 'sprintf', 'calendar_view_edit_select_room.html', 9, false),)), $this); ?>
<?php echo '';  echo '<div class="outerdiv"><form action="" id="form';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" onsubmit="return false;"><input type="hidden" name="action" value="calendar_action_edit_selectroom" /><div class="top_description">';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['calendar_top_descripton'])) ? $this->_run_mod_handler('sprintf', true, $_tmp, ($this->_tpl_vars['lang']['_regist']), (@_SPACE_TYPE_NAME_PUBLIC)) : sprintf($_tmp, ($this->_tpl_vars['lang']['_regist']), (@_SPACE_TYPE_NAME_PUBLIC)));  echo '</div><div align="center"><table summary="';  echo ((is_array($_tmp=@_SUMMARY_SELECTFORM)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"><tr><th class="nowrap head align-center" scope="col">';  echo $this->_tpl_vars['lang']['calendar_all_room_list'];  echo '</th><td rowspan="2" class="selectlist_arrow_btn_area nowrap align-center">';  echo '<input type="button" value="';  echo $this->_tpl_vars['lang']['_btn_add_arrow'];  echo '" onclick="commonCls.frmTransValue(this.form,\'not_enroll_room[]\',\'enroll_room[]\');" /><br /><br />';  echo '<input type="button" value="';  echo $this->_tpl_vars['lang']['_btn_del_arrow'];  echo '" onclick="commonCls.frmTransValue(this.form,\'enroll_room[]\',\'not_enroll_room[]\');" /></td><th class="nowrap head align-center" scope="col">';  echo $this->_tpl_vars['lang']['calendar_entry_room_list'];  echo '</th></tr><tr><td class="selectlist nowrap align-center valign-top"><div><input type="button" value="';  echo $this->_tpl_vars['lang']['_btn_select_all'];  echo '" onclick="commonCls.frmAllSelectList(this.form,\'not_enroll_room[]\');" />&nbsp;<input type="button" value="';  echo $this->_tpl_vars['lang']['_btn_release_all'];  echo '" onclick="commonCls.frmAllReleaseList(this.form,\'not_enroll_room[]\');" /></div><select name="not_enroll_room[]" size="14" class="calendar_selectlist" multiple="multiple" onchange="commonCls.frmAllReleaseList(this.form,\'enroll_room[]\'); return false;">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "calendar_view_recursive_room_flat.html", 'smarty_include_vars' => array('room_list' => $this->_tpl_vars['action']['not_enroll_room_arr'])));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</select></td><td class="selectlist nowrap align-center valign-top"><div><input type="button" value="';  echo $this->_tpl_vars['lang']['_btn_select_all'];  echo '" onclick="commonCls.frmAllSelectList(this.form,\'enroll_room[]\', true);" />&nbsp;<input type="button" value="';  echo $this->_tpl_vars['lang']['_btn_release_all'];  echo '" onclick="commonCls.frmAllReleaseList(this.form,\'enroll_room[]\');" /></div><select name="enroll_room[]" size="14" class="calendar_selectlist" multiple="multiple" onchange="commonCls.frmAllReleaseList(this.form,\'not_enroll_room[]\'); return false;">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "calendar_view_recursive_room_flat.html", 'smarty_include_vars' => array('room_list' => $this->_tpl_vars['action']['enroll_room_arr'])));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</select><div><label for="calendar_myroom_flag';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"><input id="calendar_myroom_flag';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" type="checkbox" name="myroom_flag" value="';  echo ((is_array($_tmp=@_ON)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['calendar_block']['myroom_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo ' checked="checked"';  endif;  echo ' />';  echo $this->_tpl_vars['lang']['calendar_myroom_flag'];  echo '</label></div></td></tr></table></div><br /><div class="note">';  echo $this->_tpl_vars['lang']['_mes_pluralselecthelp'];  echo '</div><div class="btn-bottom"><input class="btn-width lined_btn" type="button" value="';  echo $this->_tpl_vars['lang']['_regist'];  echo '" onclick="calendarCls[\'';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '\'].setSelectRoom(this.form); return false;" /><input class="btn-width lined_btn" type="button" value="';  echo $this->_tpl_vars['lang']['_cancel'];  echo '" onclick="commonCls.removeBlock(\'';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '\'); return false;" /></div></form></div>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../calendar_script.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo ''; ?>