<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:33
         compiled from journal_mobile_post.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'journal_mobile_post.html', 3, false),array('modifier', 'timezone_date_format', 'journal_mobile_post.html', 12, false),)), $this); ?>
<?php echo '<form method="post" action="./';  echo ((is_array($_tmp=$this->_tpl_vars['smaryt']['const']['INDEX_FILE_NAME'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" ';  if (((is_array($_tmp=$_SESSION['_mobile_info']['currier'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != 'EZweb'):  echo 'enctype="multipart/form-data"';  endif;  echo '  data-ajax="false"><div><input type="hidden" name="action" value="journal_action_mobile_post"><input type="hidden" name="block_id" value="';  echo ((is_array($_tmp=$this->_tpl_vars['block_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"><input type="hidden" name="j_id" value="';  echo ((is_array($_tmp=$this->_tpl_vars['action']['journal_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['post']['post_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) > 0 )):  echo '<input type="hidden" name="p_id" value="';  echo ((is_array($_tmp=$this->_tpl_vars['action']['post']['post_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  endif;  echo '';  $this->assign('journal_date', ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['action']['post']['journal_date'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))) ? $this->_run_mod_handler('timezone_date_format', true, $_tmp, 'YmdHis') : timezone_date_format($_tmp, 'YmdHis')));  echo '';  if (( ((is_array($_tmp=$_SESSION['_smartphone_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "journal_mobile_post_smart.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  else:  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "journal_mobile_post_feature.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  endif;  echo '<input data-role="button" data-inline="true" type="submit" name="temporary" value="';  echo $this->_tpl_vars['lang']['_temporary'];  echo '"><input data-role="button" data-inline="true" type="submit" name="regist" value="';  echo $this->_tpl_vars['lang']['_regist'];  echo '"><input data-role="button" data-inline="true" type="submit" name="cancel" value="';  echo $this->_tpl_vars['lang']['_cancel'];  echo '">';  echo $this->_tpl_vars['token_form'];  echo '';  echo $this->_tpl_vars['session_form'];  echo '</div></form>'; ?>