<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:33
         compiled from menu_mobile_init.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'menu_mobile_init.html', 4, false),)), $this); ?>
<?php echo '';  echo '';  if (( ((is_array($_tmp=$_SESSION['_smartphone_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '<ul data-role="listview" data-inset="false" data-divider-theme="';  echo ((is_array($_tmp=$this->_tpl_vars['smartphone_theme_color'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" ><li data-role="list-divider">';  echo $this->_tpl_vars['lang']['menu_page_select'];  echo '</li>';  else:  echo '<h3>';  echo $this->_tpl_vars['lang']['menu_page_select'];  echo '</h3><div>';  endif;  echo '';  if (! empty ( $this->_tpl_vars['action']['pageTree'] )):  echo '';  $this->assign('pages', ((is_array($_tmp=$this->_tpl_vars['action']['topPage'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')));  echo '';  $this->assign('minusIndentFirstCheckLevel', 1);  echo '';  $this->assign('minusIndentFirst', 0);  echo '';  if (( ((is_array($_tmp=$_SESSION['_smartphone_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '';  if (((is_array($_tmp=$this->_tpl_vars['action']['menu_display_type'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == ((is_array($_tmp=@MOBILE_MENU_DISPLAY_TREE)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))):  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "menu_mobile_recursive_page_smart_tree.html", 'smarty_include_vars' => array('page_counter_param' => ((is_array($_tmp=$this->_tpl_vars['page_counter_param'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  else:  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "menu_mobile_recursive_page_smart_flat.html", 'smarty_include_vars' => array('page_counter_param' => ((is_array($_tmp=$this->_tpl_vars['page_counter_param'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  endif;  echo '';  else:  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "menu_mobile_recursive_page_feature.html", 'smarty_include_vars' => array('page_counter_param' => ((is_array($_tmp=$this->_tpl_vars['page_counter_param'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  endif;  echo '';  else:  echo '';  echo $this->_tpl_vars['lang']['menu_no_page'];  echo '';  endif;  echo '';  if (( ((is_array($_tmp=$_SESSION['_smartphone_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '</ul><br />';  else:  echo '</div>';  endif;  echo '<br />';  if (((is_array($_tmp=$this->_tpl_vars['action']['each_room_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == ((is_array($_tmp=@_ON)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))):  echo '';  if (( ((is_array($_tmp=$_SESSION['_smartphone_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '<ul data-role="listview" data-inset="false" data-theme="a" data-divider-theme="a"><li data-role="list-divider">';  echo $this->_tpl_vars['lang']['menu_room_select'];  echo '</li>';  else:  echo '<h3>';  echo $this->_tpl_vars['lang']['menu_room_select'];  echo '</h3>';  endif;  echo '';  $this->assign('menu_redirect_action', ((is_array($_tmp=$this->_tpl_vars['conf']['menu_redirect_action'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')));  echo '';  $this->assign('next_thread_num', 0);  echo '';  $this->assign('next_parent_id', 0);  echo '';  $this->assign('room_list', ((is_array($_tmp=$this->_tpl_vars['action']['room_arr'][$this->_tpl_vars['next_thread_num']][$this->_tpl_vars['next_parent_id']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')));  echo '';  if (( ((is_array($_tmp=$_SESSION['_smartphone_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "menu_mobile_recursive_room_smart.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</ul>';  else:  echo '<div>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "menu_mobile_recursive_room_feature.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</div>';  endif;  echo '<br />';  endif;  echo ''; ?>