<?php /* Smarty version 2.6.12, created on 2013-07-11 10:33:45
         compiled from menu_view_main_edit.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'menu_view_main_edit.html', 5, false),array('modifier', 'get_themes_image', 'menu_view_main_edit.html', 6, false),)), $this); ?>
<?php echo '<form onsubmit="return false;"><div class="menu_top_menu"><span class="menu_top_menu_btn"><a class="_menu_header_btn syslink" href="#" onclick="menuCls[\'';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '\'].insPage(1); return false;"><img class="icon" src="';  echo ((is_array($_tmp="add_folder.gif")) ? $this->_run_mod_handler('get_themes_image', true, $_tmp) : get_themes_image($_tmp));  echo '" alt="" title="';  echo $this->_tpl_vars['lang']['menu_add_category'];  echo '"/>&nbsp;';  echo '';  echo $this->_tpl_vars['lang']['menu_add_category'];  echo '</a>';  echo '</span><span class="menu_top_menu_btn"><a class="_menu_header_btn syslink" href="#" onclick="menuCls[\'';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '\'].insPage(); return false;"><img class="icon" src="';  echo ((is_array($_tmp="add_file.gif")) ? $this->_run_mod_handler('get_themes_image', true, $_tmp) : get_themes_image($_tmp));  echo '" alt="" title="';  echo $this->_tpl_vars['lang']['menu_add_page'];  echo '"/>&nbsp;';  echo '';  echo $this->_tpl_vars['lang']['menu_add_page'];  echo '</a>';  echo '</span></div>';  $this->assign('menus', ((is_array($_tmp=$this->_tpl_vars['action']['menus']['0']['0'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')));  echo '';  $this->assign('visibility_flag', 1);  echo '<div class="outerdiv" id="_menu_range';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "menu_view_edit_list.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</div></form>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "menu_script.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo ''; ?>