<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:53
         compiled from page.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'page.html', 16, false),)), $this); ?>
<?php echo '';  echo '<table id="_container" class="container" summary="" ';  if (((is_array($_tmp=$this->_tpl_vars['align'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != 'left'):  echo 'align="';  echo ((is_array($_tmp=$this->_tpl_vars['align'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" ';  endif;  echo 'style="text-align:';  echo ((is_array($_tmp=$this->_tpl_vars['align'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo ';';  if (((is_array($_tmp=$this->_tpl_vars['leftmargin'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != 0):  echo 'margin-left:';  echo ((is_array($_tmp=$this->_tpl_vars['leftmargin'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo 'px;';  endif;  echo '';  if (((is_array($_tmp=$this->_tpl_vars['rightmargin'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != 0):  echo 'margin-right:';  echo ((is_array($_tmp=$this->_tpl_vars['rightmargin'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo 'px;';  endif;  echo '';  if (((is_array($_tmp=$this->_tpl_vars['topmargin'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != 0):  echo 'margin-top:';  echo ((is_array($_tmp=$this->_tpl_vars['topmargin'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo 'px;';  endif;  echo '';  if (((is_array($_tmp=$this->_tpl_vars['bottommargin'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != 0):  echo 'margin-bottom:';  echo ((is_array($_tmp=$this->_tpl_vars['bottommargin'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo 'px;';  endif;  echo '"><tr><td class="valign-top align-left">';  if (((is_array($_tmp=$_SESSION['_header_menu_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON || ((is_array($_tmp=$_SESSION['_layoutmode'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 'on'):  echo '<div class="headercolumn_menu">';  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "headermenu.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</div>';  endif;  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../login.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  if (((is_array($_tmp=$this->_tpl_vars['main_display_position'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _DISPLAY_POSITION_CENTER && ( ((is_array($_tmp=$this->_tpl_vars['header_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) || ((is_array($_tmp=$_SESSION['_layoutmode'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 'on' )):  echo '';  if (((is_array($_tmp=$this->_tpl_vars['header_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))):  echo '<div id="_headercolumn" class="headercolumn"';  if (((is_array($_tmp=$this->_tpl_vars['header_style'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) != ""):  echo ' style="';  echo ((is_array($_tmp=$this->_tpl_vars['header_style'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"';  endif;  echo '>';  if (((is_array($_tmp=$_SESSION['_layoutmode'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 'on' && ( ((is_array($_tmp=$this->_tpl_vars['main_display_position'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _DISPLAY_POSITION_CENTER || ((is_array($_tmp=$this->_tpl_vars['main_display_position'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _DISPLAY_POSITION_HEADER )):  echo '<div id="headercolumn_addmodule" class="valign-top align-left">';  echo '';  $this->assign('arrange_position', 'header');  echo '';  $this->assign('column_page_id', ((is_array($_tmp=$_SESSION['_headercolumn_page_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')));  echo '';  $this->assign('display_position', ((is_array($_tmp=@_DISPLAY_POSITION_HEADER)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')));  echo '';  $this->assign('auth_id', ((is_array($_tmp=$_SESSION['_auth_arr'][$this->_tpl_vars['display_position']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')));  echo '';  $this->assign('addblock_field', ((is_array($_tmp=$this->_tpl_vars['addblock_header_field'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')));  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "addblock_box.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</div>';  endif;  echo '<div id="__headercolumn" class="main_column';  if (((is_array($_tmp=$_SESSION['_layoutmode'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 'on'):  echo ' headercolumn_on';  endif;  echo '">';  echo '';  echo $this->_tpl_vars['content_header_field'];  echo '</div></div>';  endif;  echo '';  endif;  echo '</td></tr>';  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "main.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  if (((is_array($_tmp=$this->_tpl_vars['main_display_position'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _DISPLAY_POSITION_CENTER && ( ((is_array($_tmp=$this->_tpl_vars['footer_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 1 || ((is_array($_tmp=$_SESSION['_layoutmode'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 'on' )):  echo '';  if (((is_array($_tmp=$this->_tpl_vars['footer_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))):  echo '<tr class="main_column" id="footercolumn"><td id="_footercolumn" class="footercolumn valign-top align-left" style="';  echo ((is_array($_tmp=$this->_tpl_vars['footer_style'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "./footer.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td></tr>';  endif;  echo '';  endif;  echo '</table>'; ?>