<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:35
         compiled from photoalbum_view_edit_list.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'sprintf', 'photoalbum_view_edit_list.html', 5, false),array('modifier', 'escape', 'photoalbum_view_edit_list.html', 5, false),array('modifier', 'timezone_date_format', 'photoalbum_view_edit_list.html', 40, false),)), $this); ?>
<?php echo '';  echo '<form action="#"><div>';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['_list_desc'])) ? $this->_run_mod_handler('sprintf', true, $_tmp, ((is_array($_tmp=$this->_tpl_vars['lang']['photoalbum_photoalbum'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))) : sprintf($_tmp, ((is_array($_tmp=$this->_tpl_vars['lang']['photoalbum_photoalbum'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))));  echo '</div><table class="grid_header" summary="';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['photoalbum_list_summary'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"><tr><th class="grid_change_disp" scope="col"></th><th class="_sort_photoalbum_name grid_name" scope="col">';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['photoalbum_photoalbum_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '</th><th class="_sort_insert_user_name grid_creator" scope="col">';  echo $this->_tpl_vars['lang']['_creator'];  echo '</th><th class="_sort_insert_time grid_create_date" scope="col">';  echo $this->_tpl_vars['lang']['_create_date'];  echo '</th><th class="photoalbum_grid_manage">';  echo $this->_tpl_vars['lang']['_manage'];  echo '</th></tr></table><table class="grid photoalbum_grid_table" summary="';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['photoalbum_list_summary'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  $_from = ((is_array($_tmp=$this->_tpl_vars['action']['photoalbums'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['photoalbum']):
 echo '<tr id="photoalbum_current_row';  echo ((is_array($_tmp=$this->_tpl_vars['photoalbum']['photoalbum_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" class="grid_row"><td class="grid_change_disp">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "photoalbum_view_edit_list_current.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td><td class="grid_name">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "photoalbum_view_edit_list_name.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td><td class="grid_creator">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "photoalbum_view_handle.html", 'smarty_include_vars' => array('handle' => $this->_tpl_vars['photoalbum']['insert_user_name'],'user_id' => ((is_array($_tmp=$this->_tpl_vars['photoalbum']['insert_user_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td><td class="grid_create_date">';  echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['photoalbum']['insert_time'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))) ? $this->_run_mod_handler('timezone_date_format', true, $_tmp, ((is_array($_tmp=$this->_tpl_vars['lang']['_date_format'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))) : timezone_date_format($_tmp, ((is_array($_tmp=$this->_tpl_vars['lang']['_date_format'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))));  echo '</td><td class="photoalbum_grid_manage">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "photoalbum_view_edit_list_manage.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td></tr>';  endforeach; endif; unset($_from);  echo '</table></form>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../photoalbum_script.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '<script class="nc_script" type="text/javascript">var opts = {prefetchBuffer:false,sort:true,requestParameters:new Array("scroll=';  echo ((is_array($_tmp=@_ON)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"),onSendCallback:function() {photoalbumCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].checkCurrent();}};new compLiveGrid("';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '", ';  echo ((is_array($_tmp=$this->_tpl_vars['action']['visibleRows'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo ', ';  echo ((is_array($_tmp=$this->_tpl_vars['action']['photoalbumCount'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo ', "photoalbum_view_edit_list", opts);opts = null;photoalbumCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].currentPhotoalbumID = "';  echo ((is_array($_tmp=$this->_tpl_vars['action']['currentPhotoalbumID'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '";photoalbumCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].checkCurrent();</script>'; ?>