<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:38
         compiled from reservation_style_default_time.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'reservation_style_default_time.html', 4, false),array('modifier', 'string_format', 'reservation_style_default_time.html', 18, false),array('modifier', 'sprintf', 'reservation_style_default_time.html', 20, false),)), $this); ?>
<?php echo '<th class="nowrap" scope="row"><label for="reservation_start_time';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  echo $this->_tpl_vars['lang']['reservation_start_time'];  echo '</label></th><td class="nowrap"><label for="start_time_default';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"><input id="start_time_default';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" type="radio" name="start_time_type" value="';  echo ((is_array($_tmp=@RESERVATION_DEF_START_TIME_DEFAULT)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"';  if (( ((is_array($_tmp=$this->_tpl_vars['reserve_block']['start_time_type'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == RESERVATION_DEF_START_TIME_DEFAULT )):  echo ' checked="checked"';  endif;  echo ' onclick=\'reservationCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].switchStartTime(this.form);\' />';  echo $this->_tpl_vars['lang']['reservation_start_time_default'];  echo '</label><br /><input id="start_time_fixation';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" type="radio" name="start_time_type" value="';  echo ((is_array($_tmp=@RESERVATION_DEF_START_TIME_FIXATION)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"';  if (( ((is_array($_tmp=$this->_tpl_vars['reserve_block']['start_time_type'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == RESERVATION_DEF_START_TIME_FIXATION )):  echo ' checked="checked"';  endif;  echo ' onclick=\'reservationCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].switchStartTime(this.form);\' /><select name="start_time_fixation">';  unset($this->_sections['start_hour']);
$this->_sections['start_hour']['name'] = 'start_hour';
$this->_sections['start_hour']['loop'] = is_array($_loop=24) ? count($_loop) : max(0, (int)$_loop); unset($_loop);
$this->_sections['start_hour']['start'] = (int)0;
$this->_sections['start_hour']['step'] = ((int)1) == 0 ? 1 : (int)1;
$this->_sections['start_hour']['show'] = true;
$this->_sections['start_hour']['max'] = $this->_sections['start_hour']['loop'];
if ($this->_sections['start_hour']['start'] < 0)
    $this->_sections['start_hour']['start'] = max($this->_sections['start_hour']['step'] > 0 ? 0 : -1, $this->_sections['start_hour']['loop'] + $this->_sections['start_hour']['start']);
else
    $this->_sections['start_hour']['start'] = min($this->_sections['start_hour']['start'], $this->_sections['start_hour']['step'] > 0 ? $this->_sections['start_hour']['loop'] : $this->_sections['start_hour']['loop']-1);
if ($this->_sections['start_hour']['show']) {
    $this->_sections['start_hour']['total'] = min(ceil(($this->_sections['start_hour']['step'] > 0 ? $this->_sections['start_hour']['loop'] - $this->_sections['start_hour']['start'] : $this->_sections['start_hour']['start']+1)/abs($this->_sections['start_hour']['step'])), $this->_sections['start_hour']['max']);
    if ($this->_sections['start_hour']['total'] == 0)
        $this->_sections['start_hour']['show'] = false;
} else
    $this->_sections['start_hour']['total'] = 0;
if ($this->_sections['start_hour']['show']):

            for ($this->_sections['start_hour']['index'] = $this->_sections['start_hour']['start'], $this->_sections['start_hour']['iteration'] = 1;
                 $this->_sections['start_hour']['iteration'] <= $this->_sections['start_hour']['total'];
                 $this->_sections['start_hour']['index'] += $this->_sections['start_hour']['step'], $this->_sections['start_hour']['iteration']++):
$this->_sections['start_hour']['rownum'] = $this->_sections['start_hour']['iteration'];
$this->_sections['start_hour']['index_prev'] = $this->_sections['start_hour']['index'] - $this->_sections['start_hour']['step'];
$this->_sections['start_hour']['index_next'] = $this->_sections['start_hour']['index'] + $this->_sections['start_hour']['step'];
$this->_sections['start_hour']['first']      = ($this->_sections['start_hour']['iteration'] == 1);
$this->_sections['start_hour']['last']       = ($this->_sections['start_hour']['iteration'] == $this->_sections['start_hour']['total']);
 echo '';  $this->assign('hour', ((is_array($_tmp=((is_array($_tmp=$this->_sections['start_hour']['index'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))) ? $this->_run_mod_handler('string_format', true, $_tmp, "%02d00") : smarty_modifier_string_format($_tmp, "%02d00")));  echo '<option value="';  echo ((is_array($_tmp=$this->_tpl_vars['hour'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"';  if (( ((is_array($_tmp=$this->_tpl_vars['hour'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == ((is_array($_tmp=$this->_tpl_vars['reserve_block']['start_time_hour'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) )):  echo ' selected="selected"';  endif;  echo '>';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['reservation_hour'])) ? $this->_run_mod_handler('sprintf', true, $_tmp, ($this->_sections['start_hour']['index'])) : sprintf($_tmp, ($this->_sections['start_hour']['index'])));  echo '</option>';  endfor; endif;  echo '</select><label for="start_time_fixation';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  echo $this->_tpl_vars['lang']['reservation_start_time_fixation'];  echo '</label></td>'; ?>