<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:38
         compiled from reservation_view_main_init_location.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'reservation_view_main_init_location.html', 3, false),array('modifier', 'timezone_date', 'reservation_view_main_init_location.html', 32, false),array('modifier', 'sprintf', 'reservation_view_main_init_location.html', 47, false),)), $this); ?>
<?php echo '';  $this->assign('view_date', ((is_array($_tmp=$this->_tpl_vars['action']['view_date'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')));  echo '<div class="reservation_each_location">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "reservation_main_header_location.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '<div class="reservation_move_week">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "reservation_main_move_week.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</div><table id="reservation_location';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" class="reservation_reserve_body" summary="';  echo $this->_tpl_vars['lang']['reservation_summary'];  echo '"><tr><td colspan="2" class="reservation_location_time_head">';  if (((is_array($_tmp=$this->_tpl_vars['action']['reserve_block']['display_timeframe'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == ((is_array($_tmp=@_ON)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))):  echo '<div>&nbsp;</div>';  endif;  echo '<div>&nbsp;</div></td><td rowspan="';  echo ((is_array($_tmp=$this->_tpl_vars['action']['rowspan'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"><div id="reservation_time_frame';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '" class="reservation_time_frame" style="width:';  echo ((is_array($_tmp=$this->_tpl_vars['action']['frame_width'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo 'px;"><table summary="">';  if (((is_array($_tmp=$this->_tpl_vars['action']['reserve_block']['display_timeframe'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == ((is_array($_tmp=@_ON)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))):  echo '<tr><th colspan="24"><div class="reservation_timeframe_wrapper" >';  $this->assign('start_pos', 0);  echo '';  $_from = ((is_array($_tmp=$this->_tpl_vars['action']['timeframe_list'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['timeframe']):
 echo '';  $this->assign('spacer_width', ($this->_tpl_vars['timeframe']['left']-$this->_tpl_vars['start_pos']));  echo '<div class="reservation_timeframe_spacer" style="width:';  echo ((is_array($_tmp=$this->_tpl_vars['spacer_width'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo 'px;"></div><div class="reservation_timeframe_label" style="width:';  echo ((is_array($_tmp=$this->_tpl_vars['timeframe']['width']-2)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo 'px;background-color:';  if (((is_array($_tmp=$this->_tpl_vars['timeframe']['timeframe_color'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == ""):  echo 'transparent';  else:  echo '';  echo ((is_array($_tmp=$this->_tpl_vars['timeframe']['timeframe_color'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '';  endif;  echo '" title="';  echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['timeframe']['start_time'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))) ? $this->_run_mod_handler('timezone_date', true, $_tmp, false, ((is_array($_tmp=$this->_tpl_vars['lang']['_short_time_format'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))) : timezone_date($_tmp, false, ((is_array($_tmp=$this->_tpl_vars['lang']['_short_time_format'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))));  echo '';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['reservation_time_pause'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '';  echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['timeframe']['end_time'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))) ? $this->_run_mod_handler('timezone_date', true, $_tmp, false, ((is_array($_tmp=$this->_tpl_vars['lang']['_short_time_format'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))) : timezone_date($_tmp, false, ((is_array($_tmp=$this->_tpl_vars['lang']['_short_time_format'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))));  echo '">';  echo ((is_array($_tmp=$this->_tpl_vars['timeframe']['timeframe_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '</div>';  $this->assign('start_pos', ((is_array($_tmp=$this->_tpl_vars['timeframe']['left']+$this->_tpl_vars['timeframe']['width'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')));  echo '';  endforeach; endif; unset($_from);  echo '</div></th></tr>';  endif;  echo '<tr>';  unset($this->_sections['hour']);
$this->_sections['hour']['name'] = 'hour';
$this->_sections['hour']['loop'] = is_array($_loop=24) ? count($_loop) : max(0, (int)$_loop); unset($_loop);
$this->_sections['hour']['start'] = (int)0;
$this->_sections['hour']['step'] = ((int)1) == 0 ? 1 : (int)1;
$this->_sections['hour']['show'] = true;
$this->_sections['hour']['max'] = $this->_sections['hour']['loop'];
if ($this->_sections['hour']['start'] < 0)
    $this->_sections['hour']['start'] = max($this->_sections['hour']['step'] > 0 ? 0 : -1, $this->_sections['hour']['loop'] + $this->_sections['hour']['start']);
else
    $this->_sections['hour']['start'] = min($this->_sections['hour']['start'], $this->_sections['hour']['step'] > 0 ? $this->_sections['hour']['loop'] : $this->_sections['hour']['loop']-1);
if ($this->_sections['hour']['show']) {
    $this->_sections['hour']['total'] = min(ceil(($this->_sections['hour']['step'] > 0 ? $this->_sections['hour']['loop'] - $this->_sections['hour']['start'] : $this->_sections['hour']['start']+1)/abs($this->_sections['hour']['step'])), $this->_sections['hour']['max']);
    if ($this->_sections['hour']['total'] == 0)
        $this->_sections['hour']['show'] = false;
} else
    $this->_sections['hour']['total'] = 0;
if ($this->_sections['hour']['show']):

            for ($this->_sections['hour']['index'] = $this->_sections['hour']['start'], $this->_sections['hour']['iteration'] = 1;
                 $this->_sections['hour']['iteration'] <= $this->_sections['hour']['total'];
                 $this->_sections['hour']['index'] += $this->_sections['hour']['step'], $this->_sections['hour']['iteration']++):
$this->_sections['hour']['rownum'] = $this->_sections['hour']['iteration'];
$this->_sections['hour']['index_prev'] = $this->_sections['hour']['index'] - $this->_sections['hour']['step'];
$this->_sections['hour']['index_next'] = $this->_sections['hour']['index'] + $this->_sections['hour']['step'];
$this->_sections['hour']['first']      = ($this->_sections['hour']['iteration'] == 1);
$this->_sections['hour']['last']       = ($this->_sections['hour']['iteration'] == $this->_sections['hour']['total']);
 echo '';  $this->assign('hour', ((is_array($_tmp=$this->_sections['hour']['index'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')));  echo '<th class="reservation_background reservation_time_width" scope="col"><div class="reservation_time">';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['reservation_time_format'])) ? $this->_run_mod_handler('sprintf', true, $_tmp, ((is_array($_tmp=$this->_tpl_vars['hour'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))) : sprintf($_tmp, ((is_array($_tmp=$this->_tpl_vars['hour'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))));  echo '</div></th>';  endfor; endif;  echo '</tr>';  $_from = ((is_array($_tmp=$this->_tpl_vars['action']['location_list'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }$this->_foreach['location_list'] = array('total' => count($_from), 'iteration' => 0);
if ($this->_foreach['location_list']['total'] > 0):
    foreach ($_from as $this->_tpl_vars['location_id'] => $this->_tpl_vars['location']):
        $this->_foreach['location_list']['iteration']++;
 echo '<tr><td class="reservation_background" colspan="24">';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['reserve_data'][$this->_tpl_vars['location_id']][$this->_tpl_vars['view_date']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) )):  echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "reservation_view_main_list_location.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  else:  echo '<div class="reservation_reserve_time">&nbsp;</div>';  endif;  echo '</td></tr>';  endforeach; endif; unset($_from);  echo '</table></div></td></tr>';  $_from = ((is_array($_tmp=$this->_tpl_vars['action']['location_list'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }$this->_foreach['location_list'] = array('total' => count($_from), 'iteration' => 0);
if ($this->_foreach['location_list']['total'] > 0):
    foreach ($_from as $this->_tpl_vars['location_id'] => $this->_tpl_vars['location']):
        $this->_foreach['location_list']['iteration']++;
 echo '';  if (( ((is_array($_tmp=($this->_foreach['location_list']['iteration'] <= 1))) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) )):  echo '';  $this->assign('first_location_id', ((is_array($_tmp=$this->_tpl_vars['location_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')));  echo '';  endif;  echo '<tr><td class="reservation_location_head" scope="row"><div class="reservation_location"><a class="syslink hover_highlight" title="';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['reservation_show_details'])) ? $this->_run_mod_handler('sprintf', true, $_tmp, ((is_array($_tmp=$this->_tpl_vars['location']['location_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))) : sprintf($_tmp, ((is_array($_tmp=$this->_tpl_vars['location']['location_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))));  echo '" href="#" onclick=\'reservationCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].showLocation(event,"';  echo ((is_array($_tmp=$this->_tpl_vars['location_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"); return false;\'>';  echo ((is_array($_tmp=$this->_tpl_vars['location']['location_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '</a></div></td><td class="reservation_location_addreserve" scope="row">';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "reservation_main_addreserve.html", 'smarty_include_vars' => array('view_date' => ((is_array($_tmp=$this->_tpl_vars['view_date'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'location_id' => ((is_array($_tmp=$this->_tpl_vars['location_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')),'hour' => "")));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td></tr>';  endforeach; endif; unset($_from);  echo '<tr><td colspan="2">&nbsp;</td></tr></table>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "reservation_main_swicth_display_type.html", 'smarty_include_vars' => array('display_type' => ((is_array($_tmp=@RESERVATION_DEF_LOCATION)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</div>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "../reservation_script.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '<script class="nc_script" type="text/javascript">reservationCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].disp_type = "';  echo ((is_array($_tmp=@RESERVATION_DEF_LOCATION)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '";reservationCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].view_date = "';  echo ((is_array($_tmp=$this->_tpl_vars['view_date'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '";reservationCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].category_id = "';  echo ((is_array($_tmp=$this->_tpl_vars['action']['reserve_block']['category_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '";reservationCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].location_id = "';  echo ((is_array($_tmp=$this->_tpl_vars['first_location_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '";reservationCls["';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].today = "';  echo ((is_array($_tmp=$this->_tpl_vars['action']['today'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '";';  if (( ((is_array($_tmp=$_SESSION['reservation']['popup_move']['_id'][$this->_tpl_vars['block_id']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) )):  echo 'if(reservationCls["';  echo ((is_array($_tmp=$_SESSION['reservation']['popup_move']['_id'][$this->_tpl_vars['block_id']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"]) {reservationCls["';  echo ((is_array($_tmp=$_SESSION['reservation']['popup_move']['_id'][$this->_tpl_vars['block_id']])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '"].setMoveDate("';  echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '", "';  echo ((is_array($_tmp=$this->_tpl_vars['action']['input_date'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '");}';  endif;  echo '</script>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "reservation_main_script.html", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo ''; ?>