<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:38
         compiled from reservation_reserve_details_reserve_flag.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'reservation_reserve_details_reserve_flag.html', 7, false),array('modifier', 'get_image_url', 'reservation_reserve_details_reserve_flag.html', 14, false),array('modifier', 'sprintf', 'reservation_reserve_details_reserve_flag.html', 19, false),)), $this); ?>
<?php echo '<th class="nowrap" scope="row">';  echo $this->_tpl_vars['lang']['reservation_reserve_flag'];  echo '</th><td>';  ob_start();
$_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "reservation_main_set_reserve_class.html", 'smarty_include_vars' => array('reserve_flag' => ((is_array($_tmp=$this->_tpl_vars['action']['reserve']['reserve_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
$this->assign('reserve_class', ob_get_contents()); ob_end_clean();
  echo '<div class="';  echo ((is_array($_tmp=$this->_tpl_vars['reserve_class'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['reserve']['reserve_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == RESERVATION_MEMBERS )):  echo '';  echo $this->_tpl_vars['lang']['reservation_no_reserve_flag'];  echo '';  elseif (( ((is_array($_tmp=$this->_tpl_vars['action']['reserve']['reserve_flag'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == RESERVATION_PRIVATE )):  echo '<img src="';  echo ((is_array($_tmp="")) ? $this->_run_mod_handler('get_image_url', true, $_tmp) : get_image_url($_tmp));  echo '/images/common/blank.gif" class="icon ';  echo ((is_array($_tmp=$this->_tpl_vars['reserve_class'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo ' reservation_reserve_mark" alt="" title="" />';  echo @RESERVATION_PRIVATE_RESERVE_FLAG;  echo '';  else:  echo '<img src="';  echo ((is_array($_tmp="")) ? $this->_run_mod_handler('get_image_url', true, $_tmp) : get_image_url($_tmp));  echo '/images/common/blank.gif" class="icon ';  echo ((is_array($_tmp=$this->_tpl_vars['reserve_class'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo ' reservation_reserve_mark" alt="" title="" />';  echo ((is_array($_tmp=$this->_tpl_vars['lang']['reservation_reserve_flag_str'])) ? $this->_run_mod_handler('sprintf', true, $_tmp, ((is_array($_tmp=$this->_tpl_vars['action']['reserve']['page_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))) : sprintf($_tmp, ((is_array($_tmp=$this->_tpl_vars['action']['reserve']['page_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))));  echo '';  endif;  echo '</div></td>'; ?>
