<?php /* Smarty version 2.6.12, created on 2013-07-11 09:01:38
         compiled from todo_mobile_task_smart.html */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'todo_mobile_task_smart.html', 6, false),)), $this); ?>
<?php echo '';  echo '';  echo '<h3>';  echo ((is_array($_tmp=$this->_tpl_vars['action']['todo']['todo_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '</h3>';  echo '<div data-role="controlgroup" data-type="horizontal">';  if (((is_array($_tmp=$this->_tpl_vars['action']['target_state'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON):  echo '<a data-role="button" data-theme="c" href="?action=todo_view_main_init&amp;block_id=';  echo ((is_array($_tmp=$this->_tpl_vars['block_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '&amp;target_state=';  echo ((is_array($_tmp=@_OFF)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '';  echo ((is_array($_tmp=$this->_tpl_vars['session_param'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  echo $this->_tpl_vars['lang']['todo_mobile_state_none'];  echo '</a><a data-role="button" href="#" class="ui-btn-active ">';  echo $this->_tpl_vars['lang']['todo_mobile_state'];  echo '</a>';  else:  echo '<a data-role="button" href="#" class="ui-btn-active ">';  echo $this->_tpl_vars['lang']['todo_mobile_state_none'];  echo '</a><a data-role="button" data-theme="c" href="?action=todo_view_main_init&amp;block_id=';  echo ((is_array($_tmp=$this->_tpl_vars['block_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '&amp;target_state=';  echo ((is_array($_tmp=@_ON)) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '';  echo ((is_array($_tmp=$this->_tpl_vars['session_param'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  echo $this->_tpl_vars['lang']['todo_mobile_state'];  echo '</a>';  endif;  echo '</div><br />';  if (((is_array($_tmp=$this->_tpl_vars['action']['taskCount'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) > 0):  echo '';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['todo']['used_category'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == _ON )):  echo '<ul data-role="listview" data-theme="c" data-split-icon="delete" data-divider-theme="';  echo ((is_array($_tmp=$this->_tpl_vars['smartphone_theme_color'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  $_from = ((is_array($_tmp=$this->_tpl_vars['action']['categories'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['category']):
 echo '';  $this->assign('category_id', ((is_array($_tmp=$this->_tpl_vars['category']['category_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')));  echo '';  if (( isset ( $this->_tpl_vars['action']['tasks'][$this->_tpl_vars['category_id']] ) )):  echo '';  if (( ((is_array($_tmp=$this->_tpl_vars['category_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 0 )):  echo '<li data-role="list-divider">';  echo $this->_tpl_vars['lang']['todo_nocategory'];  echo '</li>';  else:  echo '<li data-role="list-divider">';  echo ((is_array($_tmp=$this->_tpl_vars['category']['category_name'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '</li>';  endif;  echo '';  $_from = $this->_tpl_vars['action']['tasks'][$this->_tpl_vars['category_id']]; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['task']):
 echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "todo_mobile_task_detail_smart.html", 'smarty_include_vars' => array('task' => ((is_array($_tmp=$this->_tpl_vars['task'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  endforeach; endif; unset($_from);  echo '';  endif;  echo '';  endforeach; endif; unset($_from);  echo '</ul>';  else:  echo '<ul data-role="listview" data-theme="c" data-split-icon="delete">';  $_from = $this->_tpl_vars['action']['tasks']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['task']):
 echo '';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "todo_mobile_task_detail_smart.html", 'smarty_include_vars' => array('task' => ((is_array($_tmp=$this->_tpl_vars['task'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '';  endforeach; endif; unset($_from);  echo '</ul>';  endif;  echo '';  else:  echo '<br /><br />';  echo $this->_tpl_vars['lang']['todo_no_task'];  echo '<br /><br /><br />';  endif;  echo '<br />';  if (((is_array($_tmp=$this->_tpl_vars['action']['todo']['task_authority'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'))):  echo '<a data-role="button" href="?action=todo_view_main_entry&amp;block_id=';  echo ((is_array($_tmp=$this->_tpl_vars['block_id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '';  echo ((is_array($_tmp=$this->_tpl_vars['session_param'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  echo $this->_tpl_vars['lang']['todo_add_task'];  echo '</a>';  endif;  echo '<div style="text-align:right">';  if (( ((is_array($_tmp=$this->_tpl_vars['action']['block_num'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')) == 1 )):  echo '<a href="?action=menu_view_mobile_init';  echo ((is_array($_tmp=$this->_tpl_vars['session_param'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  else:  echo '<a href="?action=menu_view_mobile_detail';  echo ((is_array($_tmp=$this->_tpl_vars['session_param'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html'));  echo '">';  endif;  echo '';  echo $this->_tpl_vars['lang']['_btn_prev_arrow'];  echo '</a></div>'; ?>